"""empty message

Revision ID: c8c247ca5932
Revises: 126b410f9e59
Create Date: 2021-08-10 04:59:04.428144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c247ca5932'
down_revision = '126b410f9e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
